//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace main_application
{
    using System;
    using System.Collections.Generic;
    
    public partial class inbox
    {
        public long id { get; set; }
        public string sender { get; set; }
        public string recepient { get; set; }
        public string re { get; set; }
        public string msg { get; set; }
        public string status { get; set; }
        public Nullable<long> foreign_id { get; set; }
        public string date_received { get; set; }
    }
}
